### ISSUE TITLE
preview_database_id 

### ISSUE THREAD

**Issue by wanghaisheng** [powerfulyang/cloudflare-worker#1]
也是d1建一个db 把id填进去吗
类似r2的bucket test

**Comment by wanghaisheng** [comment]
![image](https://github.com/user-attachments/assets/f6f9410c-0128-4bdb-b580-9710931755a2)
建了两个 id页配置了 bu's部署还是说databse不存在
  binding DB of type d1 must have a database that already exists. Use wrangler or the UI to create

**Comment by powerfulyang** [comment]
preview_database_id 是 wrangler dev --remote 时候用的，主要 database_id 要换成你自己的。看自己 d1 database 的 id，换一下。
最近的代码我在重构，不太可用。

**Comment by wanghaisheng** [comment]
嗯  我现在都弄了俩d1的  id都配上 但是说database不存在  我没有运行其他命令。
install以后直接 run deploy的

**Comment by wanghaisheng** [comment]
wrangler d1 execute eleven --file .\drizzle\0000_reflective_dracula.sql

package.json 里的eleven也要替换成DB 现在toml里面我看binding名字是DB
这样子我就部署起来了

**Comment by wanghaisheng** [comment]
刚得意3s，我发现访问这个http://[staging.api.borninsea.com](http://staging.api.borninsea.com/)/ 404.。。。

**Comment by powerfulyang** [comment]
https://staging.api.borninsea.com/api/baby/1 
,看起来你已经部署成功了，然后你还需要把表结构同步。但是现在的代码并不可用，4月份的代码是稳定的。
wrangler d1 execute eleven --file .\drizzle\0000_reflective_dracula.sql 要加 --remote，同步到远程。而且这是一个后端的 api，C端页面在另外一个仓库。

**Comment by powerfulyang** [comment]
如果要部署，有很多东西要改，现在还不是很通用。。。。有很多东西数据还有初始化，都是手动的。当前只能参考下写法，直接能拿来用的话，只能等我把代码优化了

**Comment by wanghaisheng** [comment]
嗯 我可以再扣一份4月份的commit 看看 手动也没啥关系 当下我只是把你那个baby tracker跑通
数据结构本来我就是要单独另外弄的

**Comment by wanghaisheng** [comment]
@powerfulyang 改的差不多了记得q我一下哈
